import { isSupabaseConfigured } from '../supabase';
import * as local from './dbLocal';
import * as remote from './dbSupabase';

const impl = isSupabaseConfigured ? remote : local;

export const {
  getEmployees,
  addEmployee,
  deleteEmployee,
  getProxies,
  addProxy,
  deleteProxy,
  getBios,
  addBio,
  updateBio,
  deleteBio,
  getCtas,
  addCta,
  deleteCta,
  getBanners,
  addBanner,
  updateBanner,
  deleteBanner,
  getProfilePics,
  addProfilePic,
  updateProfilePic,
  deleteProfilePic,
  getPosts,
  addPost,
  updatePost,
  deletePost,
  getBskyAccounts,
  addBskyAccount,
  deleteBskyAccount,
  getSavedAccounts,
  addSavedAccount,
  deleteSavedAccount,
  getSlaveAccounts,
  addSlaveAccount,
  deleteSlaveAccount,
  getTargets,
  addTarget,
  deleteTarget,
  getFollowEvents,
  addFollowEvent,
  addFollowEvents,
  getRuns,
  upsertRun,
  getWarmupRuns,
  upsertWarmupRun,
  deleteWarmupRun,
  requestWarmupCancel,
} = impl;
